### ISSUE TITLE
Remove @next/font

### ISSUE THREAD

**Issue by jesusmoreno24** [simrail/map-v2#23]
warn Your project has `@next/font` installed as a dependency, please use the built-in `next/font` instead. The `@next/font` package will be removed in Next.js 14. You can migrate by running `pnpm dlx @next/codemod@latest built-in-next-font .`. Read more: https://nextjs.org/docs/messages/built-in-next-font

**Comment by Julian-Louis** [comment]
Done in https://github.com/simrail/map-v2/pull/52
