### ISSUE TITLE
Signal seems to be invalid or unnamed

### ISSUE THREAD

**Issue by SparklesReal** [simrail/map-v2#43]
On the line from Kozlow to Sprowa and Starzyny the distance to signal is always 0m and does not have a name.

**Comment by derklaro** [comment]
maybe you're already aware, but just in case: API does not return information about signals that are >5km away. Information about signals should be available once the trains move into that distance.

**Comment by SparklesReal** [comment]
Did not know about that, thank you. Not much to do in that case.
