### ISSUE TITLE
View signal states on the map in real time

### ISSUE THREAD

**Issue by Over441** [simrail/map-v2#48]
A button, like the one for line speed on the map, which shows the status of signals on the map in real time (closed = red, warning = orange, open = green, etc.).

Here's an example:

![Example](https://github.com/simrail/map-v2/assets/48887024/381a0365-16ea-4dfb-8f03-010e6126cf33)

**Comment by SparklesReal** [comment]
Thank you for the suggestion, this is something I have been thinking about. I will take a deeper look into the possibility to implement it. If it is possible i'm more than happy to work on it. :)

**Comment by SparklesReal** [comment]
Unfortunately there is no signal API from what I have found. The way of implementing this might be slow. The way I would implement it is by after passing a signal mark the block as red and the one before as orange. I will look in to this a bit more but it is a stretch of a feature. I'm currently with a script logging all signals positions to be able to test this further.

**Comment by Over441** [comment]
I may have an idea. You can take it or not take it. Currently on the map, in the train and next signal information, you can see the next signal and its speed. You could probably use the speed of the signal to tell whether the track is clear or not. 

Here's a small example to give you some context:

Let's imagine a train with the number 1433 is about to pass signal L4_1433 and the speed of this signal is vmax. On the map, the route from this signal to the other is green. It passes this signal. Signal L4_1433 turns red, so the line from this signal to the other turns red too. The signal before L4_1433 turns orange, and the signal before that flashes green.

In this common situation, we know that signal L4_1433 will be marked 0km/h in the signal speed information. Based on this information, you pick up the other signal before L4_1433. When you have these two signals, you can be sure that the trace from the signal before L4_1433 to this one will be orange. For the two signals before, you can make the trace green.

I don't know if this makes much sense, but I've tried to formulate my idea and solution as best I could.

I hope it will be useful!

**Comment by SparklesReal** [comment]
> I may have an idea. You can take it or not take it. Currently on the map, in the train and next signal information, you can see the next signal and its speed. You could probably use the speed of the signal to tell whether the track is clear or not.
> 
> Here's a small example to give you some context:
> 
> Let's imagine a train with the number 1433 is about to pass signal L4_1433 and the speed of this signal is vmax. On the map, the route from this signal to the other is green. It passes this signal. Signal L4_1433 turns red, so the line from this signal to the other turns red too. The signal before L4_1433 turns orange, and the signal before that flashes green.
> 
> In this common situation, we know that signal L4_1433 will be marked 0km/h in the signal speed information. Based on this information, you pick up the other signal before L4_1433. When you have these two signals, you can be sure that the trace from the signal before L4_1433 to this one will be orange. For the two signals before, you can make the trace green.
> 
> I don't know if this makes much sense, but I've tried to formulate my idea and solution as best I could.
> 
> I hope it will be useful!

I have been thinking about it this way, I do it will be a bit hard as it requires marking the track between 2 signals and that could require custom tile server. I have "harvested" enough signal data and I will start working on something. This something might not be exactly what you meant but it tries to be a temporary compromise until I figure out a way to develop further or if anyone else does so.

**Comment by Over441** [comment]
Okay, no problem. Can't wait to see how it turns out!
