### ISSUE TITLE
Top bar and overlay buttons dark in light mode

### ISSUE THREAD

**Issue by avrdude-t** [simrail/map-v2#73]
The top navigation bar and left overlay buttons are missing a light theme.<br/>
![lightfail](https://github.com/user-attachments/assets/421d4047-9b03-48b7-b3c8-f895a53abe83)

**Comment by Over441** [comment]
I don't know if this is a good idea.
I'm afraid you won't see anything at the end, and that's why they don't have a light theme.
It's doable, but if @Julian-Louis and the others haven't made the navigation bar and the buttons on the bottom left a light theme, I think it's for a good reason.

**Comment by Over441** [comment]
Having done a test of my own, I'm not a big fan of the bar's theme.

We'll see if we can do better, but for the moment, I'm not so sure it's a good idea.

![image](https://github.com/user-attachments/assets/70b61831-7800-47db-b737-a2f02c8b5823)

**Comment by avrdude-t** [comment]
It looks fine to me, mabye adding a shadow would be nice though.

**Comment by avrdude-t** [comment]
![lightnew](https://github.com/user-attachments/assets/fb7bb998-8c8e-4e5a-8612-6b1a5e2aa6f1)

**Comment by Julian-Louis** [comment]
Hello, I appreciate the suggestion, but I don't support implementing a "dark mode" for the top navigation bar and left bottom buttons. From my tests and your screenshots, it doesn't look good, and I think it can impact the overall user experience negatively.
