### ISSUE TITLE
Code quality bot thing

### ISSUE THREAD

**Issue by SparklesReal** [simrail/map-v2#80]
It just always says 

```
Run biome ci --reporter=github
  biome ci --reporter=github
  shell: /usr/bin/bash -e {0}




ci ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × Some errors were emitted while running checks.
  

Error: Process completed with exit code 1.
```

It does not say a clear error. And this happens on code that is not even modified compared to the normal one. It also complains about imports being used as types. But once again it does not wanna give a file and line number....................

**Comment by Julian-Louis** [comment]
It actually show errors on the files pages: 
<img width="784" alt="image" src="https://github.com/user-attachments/assets/c80a0e73-2287-4f89-a499-d0062d37ce30">
Link: https://github.com/simrail/map-v2/pull/79/files

I will edit the configuration to also return errors in the console

**Comment by SparklesReal** [comment]
To me some of this stuff does not even fit in this project. The code quality thing tells me that I NEED to add caption to a video that does not even have any use for it. This is just stupid.

**Comment by SparklesReal** [comment]
I don't get what to do when I get a exited with 1, without giving any error?

**Comment by SparklesReal** [comment]
Also #79 now has uneeded and dumb code just to make the code quality bot happy about captions.

**Comment by Julian-Louis** [comment]
@SparklesReal Can you clone the project, then run `pnpm run check`, then you should see the list of issues.
The command `pnpm run fix`, can fix some of the these issues.

Fyi I also updated the CI workflow, and the output should be better (rebase your branch if you want to see)

**Comment by SparklesReal** [comment]
> @SparklesReal Can you clone the project, then run `pnpm run check`, then you should see the list of issues. The command `pnpm run fix`, can fix some of the these issues.
> 
> Fyi I also updated the CI workflow, and the output should be better (rebase your branch if you want to see)

That update was very much needed. I have now fixed all of my branches.
