### ISSUE TITLE
Game update 2024-12-13

### ISSUE THREAD

**Issue by ShiralynDev** [simrail/map-v2#87]
The game will leave early access 13:th of December and there are some files that needs to be updated.

This need to be updated to support the steam locomotive, new wagon versions, new EMU versions
packages/map/components/railcars.json

Need to fetch all new signal for the route to Krakow, 80's route and Lodz route. The script I used to fetch them is long gone but it was a simple python script grabbing the data from all servers and seeing if a train is <1 meter away from the signal and adding that signal data to the json file.
packages/map/components/signals.json

Needs to be updated for Lodz, 80's route and Krakow route. I think that https://github.com/T-cave added some of them in his fork and they can be taken from there if he does not add them himself. 
packages/map/components/stations.json

Needs to be updated with the new train images, last time they where found in the simrail folder in steamapps
packages/map/public/trains

Most of the stuff might be easier to do after the update is out but I just wanted to document everything needed.

**Comment by derklaro** [comment]
I will update the railcar data and train images

**Comment by bendonderer** [comment]
I will update stations.json

**Comment by derklaro** [comment]
Check out https://github.com/simrail/map-v2/pull/92 first, I've done some things already

**Comment by Julian-Louis** [comment]
@ShiralynDev There is a type issue occurring when Cloudflare Pages try to build the project, I need to fix it, then it will be working
[simrail-map.ea2a4ffd-6b13-411a-a8e6-a60a60b9ca17.log](https://github.com/user-attachments/files/18203318/simrail-map.ea2a4ffd-6b13-411a-a8e6-a60a60b9ca17.log)

**Comment by ShiralynDev** [comment]
> @ShiralynDev There is a type issue occurring when Cloudflare Pages try to build the project, I need to fix it, then it will be working
> ![image](https://github.com/user-attachments/assets/98c0407e-8759-4a72-8035-01ba3c003e81)
> 
> [simrail-map.ea2a4ffd-6b13-411a-a8e6-a60a60b9ca17.log](https://github.com/user-attachments/files/18203318/simrail-map.ea2a4ffd-6b13-411a-a8e6-a60a60b9ca17.log)
> 

Hope it is not too hard to fix, good luck.

**Comment by Julian-Louis** [comment]
@ShiralynDev It is fixed !
